export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS="GET_USERS"

export const ADD_NOTES_SUCCESS ="ADD_NOTES_SUCCESS"
export const GET_USER_NOTES="GET_USER_NOTES"